require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0' # Set the minimum iOS version

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyNewProject' do
  pod 'AppAuth', '>= 0.94'

  config = use_native_modules!

  # Add necessary pods with consistent paths
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  # pod 'RNAppAuth', :path => '../node_modules/react-native-app-auth'

  use_react_native!( 
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyNewProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # Ensure compatibility for CocoaPods and React Native
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
